version: '3'

services:
  db:
    image: postgres:14.3
    container_name: teslo-db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data